blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/your-username/advanced-pocketbase-mcp-server/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 📖 Documentation
    url: https://github.com/your-username/advanced-pocketbase-mcp-server#readme
    about: Read the documentation for setup and usage instructions
  - name: 🔒 Security Issues
    url: https://github.com/your-username/advanced-pocketbase-mcp-server/security/policy
    about: Report security vulnerabilities privately
